name: Scheduled and Manual Test Run

on:
  workflow_dispatch:  # Cho phép chạy thủ công
  schedule:           # Lên lịch chạy định kỳ
    - cron: '0 2 * * *'  # Chạy hàng ngày lúc 09:00 sáng (giờ VN là UTC+7)

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install NuGet CLI
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages (sử dụng .sln)
      run: nuget restore BaiTapFPT.sln

    - name: Build solution
      run: dotnet build BaiTapFPT.sln --configuration Release

    - name: Run tests and export TRX report
      run: |
        mkdir TestResults
        dotnet test BaiTapFPT.sln --no-build --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

    - name: Upload test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: NUnit-TRX-Report
        path: TestResults/test-results.trx

    - name: Publish test results in GitHub UI
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: TestResults/test-results.trx
