name: Manual Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  

    - name: Install NuGet CLI
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages 
      run: nuget restore BaiTapFPT.sln

    - name: Build solution
      run: dotnet build BaiTapFPT.sln --configuration Release

    - name: Run tests
      run: dotnet test BaiTapFPT.sln --no-build --verbosity normal
