name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Chạy tự động mỗi ngày lúc 0:00 UTC (07:00 sáng giờ Việt Nam)
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Restore NuGet packages
      run: nuget restore BaiTapFPT.sln

    - name: Build solution
      run: msbuild BaiTapFPT.sln /p:Configuration=Release

    - name: Run unit tests using dotnet test
      run: dotnet test BaiTapFPT\BaiTapFPT.csproj --configuration Release --logger "trx"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: '**/TestResults/*.trx'
